import type { ProgressTestDefinition } from "../types";

export const masteryTest01: ProgressTestDefinition = {
  id: "mt-01",
  title: "اختبار الإتقان 1",
  subtitle: "حصيلة الأعداد والصحة والمسارات",
  coveredLessons: [21,22,23,24,25,26,27,28,29,30,31,32],
  passingScore: 70,
  skills: [
    { id: "length-measurement", label: "الطول والقياس" },
    { id: "paths-spatial", label: "المسارات والفضاء" },
    { id: "add-subtract", label: "الجمع والطرح" },
    { id: "health-food-mastery", label: "الصحة والغذاء" },
    { id: "number-compose", label: "تمثيل العدد وتفكيكه" },
  ],
  activities: [
    {
      id: "mt01_q01", type: "choice", lessonRefs: [21],
      skillId: "length-measurement", difficulty: "basic",
      prompt: "اخْتَرِ الْقَلَمَ الأَطْوَلَ.",
      audioKey: "q01_longer_pencil",
      options: [
        { id: "long", label: "الْقَلَمُ الطَّوِيل", visual: "━━━━━━━✏️" },
        { id: "short", label: "الْقَلَمُ الْقَصِير", visual: "━━━✏️" },
      ],
      correctOptionId: "long",
    },
    {
      id: "mt01_q02", type: "choice", lessonRefs: [21,22],
      skillId: "length-measurement", difficulty: "application",
      prompt: "أَيُّ شَرِيطٍ أَقْصَرُ؟",
      audioKey: "q02_shorter_ribbon",
      options: [
        { id: "a", label: "الشَّرِيطُ أ", visual: "🎀━━━━━━" },
        { id: "b", label: "الشَّرِيطُ ب", visual: "🎀━━━" },
        { id: "same", label: "مُتَسَاوِيَان" },
      ],
      correctOptionId: "b",
    },
    {
      id: "mt01_q03", type: "choice", lessonRefs: [22,23],
      skillId: "paths-spatial", difficulty: "basic",
      prompt: "اخْتَرِ السَّهْمَ الَّذِي يَدُلُّ عَلَى الْيَمِينِ.",
      audioKey: "q03_arrow_right",
      options: [
        { id: "right", label: "يَمِين", visual: "➡️" },
        { id: "left", label: "يَسَار", visual: "⬅️" },
        { id: "up", label: "فَوْق", visual: "⬆️" },
      ],
      correctOptionId: "right",
    },
    {
      id: "mt01_q04", type: "order", lessonRefs: [22,23,24],
      skillId: "paths-spatial", difficulty: "application",
      prompt: "رَتِّبْ خُطُوَاتِ الْمَسَارِ: يَمِين، ثُمَّ فَوْق، ثُمَّ يَسَار.",
      audioKey: "q04_order_path",
      tokens: ["يَسَار","يَمِين","فَوْق"],
      correctOrder: ["يَمِين","فَوْق","يَسَار"],
    },
    {
      id: "mt01_q05", type: "choice", lessonRefs: [24,25],
      skillId: "add-subtract", difficulty: "basic",
      prompt: "احْسُبْ: ثَلَاثَةٌ زَائِدُ اثْنَيْنِ.",
      audioKey: "q05_add_3_2",
      visual: "🍎🍎🍎  +  🍎🍎",
      options: [
        { id: "4", label: "4" },
        { id: "5", label: "5" },
        { id: "6", label: "6" },
      ],
      correctOptionId: "5",
    },
    {
      id: "mt01_q06", type: "choice", lessonRefs: [25,26],
      skillId: "add-subtract", difficulty: "basic",
      prompt: "احْسُبْ: سَبْعَةٌ نَاقِصُ ثَلَاثَةٍ.",
      audioKey: "q06_sub_7_3",
      options: [
        { id: "3", label: "3" },
        { id: "4", label: "4" },
        { id: "5", label: "5" },
      ],
      correctOptionId: "4",
    },
    {
      id: "mt01_q07", type: "choice", lessonRefs: [24,25,27],
      skillId: "add-subtract", difficulty: "application",
      prompt: "مَعَ تَالِين خَمْسُ تُفَّاحَاتٍ، أَضَافَتْ أَرْبَعًا. كَمْ أَصْبَحَ عِنْدَهَا؟",
      audioKey: "q07_add_apples",
      options: [
        { id: "8", label: "8" },
        { id: "9", label: "9" },
        { id: "10", label: "10" },
      ],
      correctOptionId: "9",
    },
    {
      id: "mt01_q08", type: "choice", lessonRefs: [25,26,27],
      skillId: "add-subtract", difficulty: "application",
      prompt: "كَانَتْ عَشْرُ بَالُونَاتٍ، طَارَتْ ثَلَاثٌ. كَمْ بَقِيَ؟",
      audioKey: "q08_sub_balloons",
      options: [
        { id: "6", label: "6" },
        { id: "7", label: "7" },
        { id: "8", label: "8" },
      ],
      correctOptionId: "7",
    },
    {
      id: "mt01_q09", type: "choice", lessonRefs: [28,29],
      skillId: "health-food-mastery", difficulty: "basic",
      prompt: "اخْتَرْ فُطُورًا صِحِّيًّا.",
      audioKey: "q09_healthy_breakfast",
      options: [
        { id: "healthy", label: "حَلِيبٌ وَخُبْزٌ وَفَاكِهَة", visual: "🥛🥖🍎" },
        { id: "candy", label: "حَلْوَيَاتٌ فَقَط", visual: "🍬🍭" },
        { id: "soda", label: "مَشْرُوبٌ غَازِيٌّ فَقَط", visual: "🥤" },
      ],
      correctOptionId: "healthy",
    },
    {
      id: "mt01_q10", type: "choice", lessonRefs: [28,29,30],
      skillId: "health-food-mastery", difficulty: "application",
      prompt: "بَعْدَ اللَّعِبِ، مَاذَا تَخْتَارُ لِتَحَافِظَ عَلَى صِحَّتِكَ؟",
      audioKey: "q10_after_play",
      options: [
        { id: "water", label: "أَشْرَبُ الْمَاءَ وَأَرْتَاحُ", visual: "💧🙂" },
        { id: "sweets", label: "آكُلُ حَلْوَيَاتٍ كَثِيرَة", visual: "🍬🍬🍬" },
        { id: "nothing", label: "لَا أَشْرَبُ شَيْئًا" },
      ],
      correctOptionId: "water",
    },
    {
      id: "mt01_q11", type: "choice", lessonRefs: [30,31],
      skillId: "number-compose", difficulty: "basic",
      prompt: "أَيُّ عَمَلِيَّةٍ تُكَوِّنُ الْعَدَدَ ثَمَانِيَةَ؟",
      audioKey: "q11_compose_eight",
      options: [
        { id: "5+3", label: "5 + 3" },
        { id: "5+2", label: "5 + 2" },
        { id: "4+3", label: "4 + 3" },
      ],
      correctOptionId: "5+3",
    },
    {
      id: "mt01_q12", type: "choice", lessonRefs: [30,31,32],
      skillId: "number-compose", difficulty: "application",
      prompt: "اخْتَرِ التَّفْكِيكَ الصَّحِيحَ لِلْعَدَدِ تِسْعَةٍ.",
      audioKey: "q12_decompose_nine",
      options: [
        { id: "6+3", label: "9 = 6 + 3" },
        { id: "6+2", label: "9 = 6 + 2" },
        { id: "5+3", label: "9 = 5 + 3" },
      ],
      correctOptionId: "6+3",
    },
    {
      id: "mt01_q13", type: "choice", lessonRefs: [21,24,25],
      skillId: "paths-spatial", difficulty: "transfer",
      prompt: "سَارَ خَلِيلُ خُطْوَتَيْنِ يَمِينًا ثُمَّ ثَلَاثَ خُطُوَاتٍ فَوْقَ. كَمْ خُطْوَةً سَارَ؟",
      audioKey: "q13_path_total",
      options: [
        { id: "4", label: "4" },
        { id: "5", label: "5" },
        { id: "6", label: "6" },
      ],
      correctOptionId: "5",
    },
    {
      id: "mt01_q14", type: "choice", lessonRefs: [26,28,29],
      skillId: "health-food-mastery", difficulty: "transfer",
      prompt: "فِي السَّلَّةِ ثَمَانِي فَوَاكِهَ. أَكَلَ الطِّفْلُ اثْنَتَيْنِ. كَمْ فَاكِهَةً بَقِيَتْ؟",
      audioKey: "q14_fruit_subtract",
      options: [
        { id: "5", label: "5" },
        { id: "6", label: "6" },
        { id: "7", label: "7" },
      ],
      correctOptionId: "6",
    },
    {
      id: "mt01_q15", type: "choice", lessonRefs: [21,31,32],
      skillId: "length-measurement", difficulty: "transfer",
      prompt: "حَبْلٌ طُولُهُ تِسْعُ وَحَدَاتٍ، وَآخَرُ طُولُهُ سِتُّ وَحَدَاتٍ. أَيُّ بَطَاقَةٍ صَحِيحَة؟",
      audioKey: "q15_rope_compare",
      options: [
        { id: "nine-longer", label: "حَبْلُ 9 أَطْوَلُ" },
        { id: "six-longer", label: "حَبْلُ 6 أَطْوَلُ" },
        { id: "same", label: "مُتَسَاوِيَان" },
      ],
      correctOptionId: "nine-longer",
    },
  ],
};
