import type { ProgressTestDefinition } from "../types";

export const progressTest01: ProgressTestDefinition = {
  id: "pt-01",
  title: "اختبار التقدم 1",
  subtitle: "مغامرة الأعداد والحواس",
  coveredLessons: [1,2,3,4,5,6,7,8,9,10],
  passingScore: 70,
  skills: [
    { id: "numbers-quantity", label: "الأعداد والكميات" },
    { id: "comparison-order", label: "المقارنة والترتيب" },
    { id: "spatial", label: "المواقع في الفضاء" },
    { id: "senses", label: "الحواس" },
  ],
  activities: [
    {
      id: "pt01_q01", type: "choice", lessonRefs: [1],
      skillId: "numbers-quantity", difficulty: "basic",
      prompt: "عُدَّ الفَرَاوِلَاتِ، ثُمَّ اخْتَرِ العَدَدَ الْمُنَاسِبَ.",
      audioKey: "q01_count_strawberries", visual: "🍓 🍓 🍓 🍓",
      options: [{id:"3",label:"3"},{id:"4",label:"4"},{id:"5",label:"5"}],
      correctOptionId: "4",
    },
    {
      id: "pt01_q02", type: "tap-count", lessonRefs: [5,6,10],
      skillId: "numbers-quantity", difficulty: "application",
      prompt: "ضَعْ سِتَّ كُرَاتٍ دَاخِلَ الصُّنْدُوقِ.",
      audioKey: "q02_make_six", visual: "📦",
      items: ["⚽","⚽","⚽","⚽","⚽","⚽","⚽","⚽"], correctCount: 6,
    },
    {
      id: "pt01_q03", type: "choice", lessonRefs: [5,6,8],
      skillId: "numbers-quantity", difficulty: "basic",
      prompt: "عُدَّ الأَسْمَاكَ، ثُمَّ اخْتَرِ العَدَدَ الْمُنَاسِبَ.",
      audioKey: "q03_count_fish", visual: "🐟 🐟 🐟 🐟 🐟 🐟 🐟 🐟",
      options: [{id:"6",label:"6"},{id:"8",label:"8"},{id:"9",label:"9"}],
      correctOptionId: "8",
    },
    {
      id: "pt01_q04", type: "order", lessonRefs: [1,8],
      skillId: "comparison-order", difficulty: "application",
      prompt: "رَتِّبِ الأَعْدَادَ مِنَ الأَصْغَرِ إِلَى الأَكْبَرِ.",
      audioKey: "q04_order_numbers",
      tokens: ["7","5","8","6"], correctOrder: ["5","6","7","8"],
    },
    {
      id: "pt01_q05", type: "choice", lessonRefs: [4],
      skillId: "comparison-order", difficulty: "application",
      prompt: "قَارِنِ الْمَجْمُوعَةَ الأُولَى بِالْمَجْمُوعَةِ الثَّانِيَةِ.",
      audioKey: "q05_compare_groups", visual: "⭐⭐⭐⭐⭐⭐\n⚽⚽⚽⚽",
      options: [{id:"more",label:"أَكْثَر"},{id:"less",label:"أَقَلّ"},{id:"equal",label:"يُسَاوِي"}],
      correctOptionId: "more",
    },
    {
      id: "pt01_q06", type: "choice", lessonRefs: [9],
      skillId: "spatial", difficulty: "basic",
      prompt: "أَيْنَ الْقِطَّةُ بِالنِّسْبَةِ إِلَى الْكُرْسِيِّ؟",
      audioKey: "q06_cat_position", visual: "🪑\n🐈",
      options: [{id:"above",label:"فَوْق"},{id:"below",label:"تَحْت"}],
      correctOptionId: "below",
    },
    {
      id: "pt01_q07", type: "choice", lessonRefs: [2],
      skillId: "spatial", difficulty: "transfer",
      prompt: "اخْتَرِ الطِّفْلَ الْمَوْجُودَ أَمَامَ الشَّجَرَةِ.",
      audioKey: "q07_in_front_of_tree", visual: "🌳",
      options: [
        {id:"front",label:"الطِّفْلُ 1",visual:"🧒 🌳"},
        {id:"behind",label:"الطِّفْلُ 2",visual:"🌳 🧒"},
        {id:"side",label:"الطِّفْلُ 3",visual:"🧒   🌳"},
      ],
      correctOptionId: "front",
    },
    {
      id: "pt01_q08", type: "choice", lessonRefs: [3,7],
      skillId: "senses", difficulty: "basic",
      prompt: "أَيُّ حَاسَّةٍ نَسْتَعْمِلُ لِسَمَاعِ صَوْتِ الْجَرَسِ؟",
      audioKey: "q08_hearing", visual: "🔔",
      options: [
        {id:"sight",label:"الرُّؤْيَة",visual:"👁️"},
        {id:"hearing",label:"السَّمْع",visual:"👂"},
        {id:"smell",label:"الشَّمّ",visual:"👃"},
      ],
      correctOptionId: "hearing",
    },
    {
      id: "pt01_q09", type: "choice", lessonRefs: [3,7],
      skillId: "senses", difficulty: "application",
      prompt: "أَيُّ عُضْوٍ نَسْتَعْمِلُهُ لِحَاسَّةِ الشَّمِّ؟",
      audioKey: "q09_smell_organ",
      options: [
        {id:"nose",label:"الأَنْف",visual:"👃"},
        {id:"ear",label:"الأُذُن",visual:"👂"},
        {id:"eye",label:"الْعَيْن",visual:"👁️"},
      ],
      correctOptionId: "nose",
    },
    {
      id: "pt01_q10", type: "choice", lessonRefs: [4,8,10],
      skillId: "numbers-quantity", difficulty: "transfer",
      prompt: "اخْتَرِ الْبِطَاقَةَ الَّتِي تَصِفُ الصُّنْدُوقَ الَّذِي فِيهِ أَلْعَابٌ أَكْثَرُ وَعَدَدَهَا الصَّحِيحَ.",
      audioKey: "q10_toy_boxes",
      visual: "🔴 🧸🧸🧸🧸🧸🧸🧸\n🔵 🚗🚗🚗🚗🚗",
      options: [
        {id:"red7",label:"الأَحْمَر — 7"},
        {id:"blue5",label:"الأَزْرَق — 5"},
        {id:"red5",label:"الأَحْمَر — 5"},
      ],
      correctOptionId: "red7",
    },
  ],
};
