import type { ProgressTestDefinition } from "../types";

export const progressTest02: ProgressTestDefinition = {
  id: "pt-02",
  title: "اختبار التقدم 2",
  subtitle: "مغامرة الحركة والصحة والأعداد",
  coveredLessons: [11,12,13,14,15,16,17,18,19,20],
  passingScore: 70,
  skills: [
    { id: "movement-health", label: "الحركة والصحة" },
    { id: "numbers-0-10", label: "الأعداد من 0 إلى 10" },
    { id: "ordinal-spatial", label: "الرتبة والعلاقات المكانية" },
    { id: "food-sequence", label: "الغذاء والمتتاليات" },
  ],
  activities: [
    {
      id: "pt02_q01", type: "choice", lessonRefs: [11],
      skillId: "movement-health", difficulty: "basic",
      prompt: "اخْتَرِ السُّلُوكَ الَّذِي يُسَاعِدُ الْجِسْمَ عَلَى النَّشَاطِ.",
      audioKey: "q01_active_body",
      options: [
        { id: "move", label: "أَتَحَرَّكُ وَأَلْعَبُ", visual: "🏃" },
        { id: "sit", label: "أَبْقَى جَالِسًا طَوِيلًا", visual: "🪑" },
        { id: "sleep", label: "أَنَامُ طُولَ النَّهَارِ", visual: "🛏️" },
      ],
      correctOptionId: "move",
    },
    {
      id: "pt02_q02", type: "choice", lessonRefs: [12,13],
      skillId: "numbers-0-10", difficulty: "basic",
      prompt: "أَيُّ سَلَّةٍ فِيهَا صِفْرُ تُفَّاحَاتٍ؟",
      audioKey: "q02_zero_basket",
      options: [
        { id: "zero", label: "0", visual: "🧺" },
        { id: "one", label: "1", visual: "🧺🍎" },
        { id: "two", label: "2", visual: "🧺🍎🍎" },
      ],
      correctOptionId: "zero",
    },
    {
      id: "pt02_q03", type: "choice", lessonRefs: [12,13],
      skillId: "numbers-0-10", difficulty: "application",
      prompt: "عُدَّ قَوَارِيرَ الْمَاءِ، ثُمَّ اخْتَرِ الْعَدَدَ الْمُنَاسِبَ.",
      audioKey: "q03_count_ten",
      visual: "💧 💧 💧 💧 💧\n💧 💧 💧 💧 💧",
      options: [
        { id: "8", label: "8" },
        { id: "9", label: "9" },
        { id: "10", label: "10" },
      ],
      correctOptionId: "10",
    },
    {
      id: "pt02_q04", type: "choice", lessonRefs: [13,14],
      skillId: "ordinal-spatial", difficulty: "application",
      prompt: "مَنْ فِي الْمَرْتَبَةِ الثَّالِثَةِ؟",
      audioKey: "q04_third_place",
      visual: "1️⃣ 🧒   2️⃣ 🧒   3️⃣ 🧒",
      options: [
        { id: "first", label: "الأَوَّل" },
        { id: "second", label: "الثَّانِي" },
        { id: "third", label: "الثَّالِث" },
      ],
      correctOptionId: "third",
    },
    {
      id: "pt02_q05", type: "choice", lessonRefs: [14],
      skillId: "ordinal-spatial", difficulty: "basic",
      prompt: "اخْتَرِ الصُّورَةَ الَّتِي فِيهَا الْكُرَةُ دَاخِلَ الصُّنْدُوقِ.",
      audioKey: "q05_inside_box",
      options: [
        { id: "inside", label: "دَاخِل", visual: "📦⚽" },
        { id: "outside", label: "خَارِج", visual: "📦   ⚽" },
      ],
      correctOptionId: "inside",
    },
    {
      id: "pt02_q06", type: "choice", lessonRefs: [15,16],
      skillId: "food-sequence", difficulty: "basic",
      prompt: "اخْتَرِ الْوَجْبَةَ الْأَنْسَبَ لِصِحَّةِ الْجِسْمِ.",
      audioKey: "q06_healthy_meal",
      options: [
        { id: "healthy", label: "وَجْبَةٌ صِحِّيَّة", visual: "🍎🥛🥖" },
        { id: "sweets", label: "حَلْوَيَاتٌ فَقَط", visual: "🍭🍬🥤" },
        { id: "chips", label: "مَقْلِيَّاتٌ فَقَط", visual: "🍟🍟" },
      ],
      correctOptionId: "healthy",
    },
    {
      id: "pt02_q07", type: "order", lessonRefs: [17,18],
      skillId: "food-sequence", difficulty: "application",
      prompt: "رَتِّبِ الأَعْدَادَ لِتُكْمِلَ الْمُتَتَالِيَةَ مِنَ السَّبْعَةِ إِلَى الْعَشَرَةِ.",
      audioKey: "q07_sequence_7_10",
      tokens: ["10","8","7","9"],
      correctOrder: ["7","8","9","10"],
    },
    {
      id: "pt02_q08", type: "choice", lessonRefs: [17,18,19],
      skillId: "food-sequence", difficulty: "application",
      prompt: "أَكْمِلِ النَّمَطَ: أَزْرَق، أَحْمَر، أَزْرَق، أَحْمَر، ثُمَّ مَاذَا؟",
      audioKey: "q08_color_pattern",
      visual: "🔵 🔴 🔵 🔴 ❓",
      options: [
        { id: "blue", label: "أَزْرَق", visual: "🔵" },
        { id: "red", label: "أَحْمَر", visual: "🔴" },
        { id: "green", label: "أَخْضَر", visual: "🟢" },
      ],
      correctOptionId: "blue",
    },
    {
      id: "pt02_q09", type: "choice", lessonRefs: [15,16,20],
      skillId: "numbers-0-10", difficulty: "transfer",
      prompt: "اخْتَرِ الْبِطَاقَةَ الَّتِي تَصِفُ الْمَجْمُوعَةَ الصِّحِّيَّةَ وَعَدَدَ عَنَاصِرِهَا.",
      audioKey: "q09_healthy_count",
      visual: "🍎 🍌 🥕\n🍭 🍬",
      options: [
        { id: "healthy3", label: "الطَّعَامُ الصِّحِّي — 3" },
        { id: "sweets2", label: "الْحَلْوَيَات — 2" },
        { id: "healthy2", label: "الطَّعَامُ الصِّحِّي — 2" },
      ],
      correctOptionId: "healthy3",
    },
    {
      id: "pt02_q10", type: "choice", lessonRefs: [11,12,13,20],
      skillId: "movement-health", difficulty: "transfer",
      prompt: "فِي السَّاحَةِ خَمْسَةُ أَطْفَالٍ يَتَحَرَّكُونَ. اخْتَرِ الْمَجْمُوعَةَ الَّتِي فِيهَا خَمْسَةُ أَطْفَالٍ.",
      audioKey: "q10_active_group_five",
      options: [
        { id: "five", label: "5 أَطْفَال", visual: "🏃🏃🏃🏃🏃" },
        { id: "four", label: "4 أَطْفَال", visual: "🏃🏃🏃🏃" },
        { id: "six", label: "6 أَطْفَال", visual: "🏃🏃🏃🏃🏃🏃" },
      ],
      correctOptionId: "five",
    },
  ],
};
