import type { EquationBuilderItem } from "../exercises-v2/EquationBuilderV2";
import { LESSON_28_EXERCISE_AUDIO_BASE } from "./lesson28_exercise1";

export { LESSON_28_EXERCISE_AUDIO_BASE };

export const LESSON_28_EXERCISE_3: EquationBuilderItem[] = [
  {
    id: "l28_e3_q1",
    title: "أَبْنِي عَمَلِيَّةَ الطَّرْحِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الطَّرْحِ الصَّحِيحَةِ.",
    question_audio_key: "ex3_q1",
    scene_image: "/lessons/v2/lesson28-minus-equals/s2.webp",
    mode: "build-equation",
    emoji: "🍬",
    before: 5,
    change: 2,
    result: 3,
    action: "sub",
    equation: ["5", "−", "2", "=", "3"],
    bank: ["2", "3", "=", "5", "−"],
    success: "أَحْسَنْتَ! بَنَيْتَ عَمَلِيَّةَ الطَّرْحِ.",
  },
  {
    id: "l28_e3_q2",
    title: "أَبْنِي عَمَلِيَّةَ الطَّرْحِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الطَّرْحِ الصَّحِيحَةِ.",
    question_audio_key: "ex3_q2",
    scene_image: "/lessons/v2/lesson28-minus-equals/s3.webp",
    mode: "build-equation",
    emoji: "🔵",
    before: 7,
    change: 3,
    result: 4,
    action: "sub",
    equation: ["7", "−", "3", "=", "4"],
    bank: ["4", "3", "7", "−", "="],
    success: "مُمْتَاز! العَمَلِيَّةُ صَحِيحَةٌ.",
  },
  {
    id: "l28_e3_q3",
    title: "أَبْنِي عَمَلِيَّةَ الطَّرْحِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الطَّرْحِ الصَّحِيحَةِ.",
    question_audio_key: "ex3_q3",
    scene_image: "/lessons/v2/lesson28-minus-equals/s4.webp",
    mode: "build-equation",
    emoji: "🌸",
    before: 8,
    change: 2,
    result: 6,
    action: "sub",
    equation: ["8", "−", "2", "=", "6"],
    bank: ["=", "6", "2", "−", "8"],
    success: "رَائِع! أَحْسَنْتَ التَّرْتِيبَ.",
  },
  {
    id: "l28_e3_q4",
    title: "أَبْنِي عَمَلِيَّةَ الطَّرْحِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الطَّرْحِ الصَّحِيحَةِ.",
    question_audio_key: "ex3_q4",
    scene_image: "/lessons/v2/lesson28-minus-equals/s5.webp",
    mode: "build-equation",
    emoji: "✏️",
    before: 9,
    change: 4,
    result: 5,
    action: "sub",
    equation: ["9", "−", "4", "=", "5"],
    bank: ["4", "=", "9", "5", "−"],
    success: "بَطَل! بَنَيْتَ العَمَلِيَّةَ كَامِلَةً.",
  },
];
