import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";
import { LESSON_25_EXERCISE_AUDIO_BASE } from "./lesson25_exercise1";

export { LESSON_25_EXERCISE_AUDIO_BASE };

export const LESSON_25_EXERCISE_2: AddSubStoryItem[] = [
  {
    id: "l25_e2_q1",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "رَحْمَةُ مَعَهَا ثَلَاثُ حَبَّاتِ حَلْوَى، أَضَفْنَا حَبَّةً.",
    question: "مَا العَمَلِيَّةُ الصَّحِيحَةُ؟",
    question_audio_key: "ex2_q1",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s2.webp",
    mode: "operation",
    emoji: "🍬",
    before: 3,
    change: 1,
    action: "add",
    options: [
      { id: "3+1", label: "3 + 1", emoji: "➕" },
      { id: "3-1", label: "3 - 1", emoji: "➖" },
      { id: "1+3", label: "1 + 3", emoji: "➕" },
    ],
    correct: "3+1",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e2_q2",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "فَاضِلٌ عِنْدَهُ سَبْعُ كُرَاتٍ، أَخَذَ ثَلَاثَ كُرَاتٍ.",
    question: "مَا العَمَلِيَّةُ الصَّحِيحَةُ؟",
    question_audio_key: "ex2_q2",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s3.webp",
    mode: "operation",
    emoji: "🔵",
    before: 7,
    change: 3,
    action: "sub",
    options: [
      { id: "7+3", label: "7 + 3", emoji: "➕" },
      { id: "7-3", label: "7 - 3", emoji: "➖" },
      { id: "3+7", label: "3 + 7", emoji: "➕" },
    ],
    correct: "7-3",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e2_q3",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "فِي السَّلَّةِ خَمْسُ كُبَّاتِ صُوفٍ، أَضَفْنَا أَرْبَعَ كُبَّاتٍ.",
    question: "مَا العَمَلِيَّةُ الصَّحِيحَةُ؟",
    question_audio_key: "ex2_q3",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s4.webp",
    mode: "operation",
    emoji: "🧶",
    before: 5,
    change: 4,
    action: "add",
    options: [
      { id: "5+4", label: "5 + 4", emoji: "➕" },
      { id: "5-4", label: "5 - 4", emoji: "➖" },
      { id: "4-5", label: "4 - 5", emoji: "➖" },
    ],
    correct: "5+4",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e2_q4",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "فِي العُلْبَةِ سِتُّ بَيْضَاتٍ، أَخَذَتْ سِيرِينُ أَرْبَعًا.",
    question: "مَا العَمَلِيَّةُ الصَّحِيحَةُ؟",
    question_audio_key: "ex2_q4",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s5.webp",
    mode: "operation",
    emoji: "🥚",
    before: 6,
    change: 4,
    action: "sub",
    options: [
      { id: "6+4", label: "6 + 4", emoji: "➕" },
      { id: "6-4", label: "6 - 4", emoji: "➖" },
      { id: "4+6", label: "4 + 6", emoji: "➕" },
    ],
    correct: "6-4",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e2_q5",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "عَلَى الطَّاوِلَةِ أَرْبَعُ حَبَّاتِ حَلْوَى، أَضَفْنَا ثَلَاثَ حَبَّاتٍ.",
    question: "مَا العَمَلِيَّةُ الصَّحِيحَةُ؟",
    question_audio_key: "ex2_q5",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s1.webp",
    mode: "operation",
    emoji: "🍬",
    before: 4,
    change: 3,
    action: "add",
    options: [
      { id: "4+3", label: "4 + 3", emoji: "➕" },
      { id: "4-3", label: "4 - 3", emoji: "➖" },
      { id: "3-4", label: "3 - 4", emoji: "➖" },
    ],
    correct: "4+3",
    success: "أَحْسَنْتَ!",
  },
];
