import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";
import { LESSON_27_EXERCISE_AUDIO_BASE } from "./lesson27_exercise1";

export { LESSON_27_EXERCISE_AUDIO_BASE };

export const LESSON_27_EXERCISE_3: AddSubStoryItem[] = [
  {
    id: "l27_e3_q1",
    title: "أَحْسِبُ المَجْمُوعَ",
    story: "عِنْدَ رَحْمَةَ ثَلَاثُ حَبَّاتِ حَلْوَى، أَضَفْنَا حَبَّةً.",
    question: "كَمْ صَارَ المَجْمُوعُ؟",
    question_audio_key: "ex3_q1",
    scene_image: "/lessons/v2/lesson27-plus-equals/s2.webp",
    mode: "result",
    emoji: "🍬",
    before: 3,
    change: 1,
    action: "add",
    options: [
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
    ],
    correct: "4",
    success: "أَحْسَنْتَ! المَجْمُوعُ أَرْبَعَةٌ.",
  },
  {
    id: "l27_e3_q2",
    title: "أَحْسِبُ المَجْمُوعَ",
    story: "مَعَ سِيرِينَ تُفَّاحَتَانِ، أَضَفْنَا تُفَّاحَتَيْنِ.",
    question: "كَمْ صَارَ المَجْمُوعُ؟",
    question_audio_key: "ex3_q2",
    scene_image: "/lessons/v2/lesson27-plus-equals/s3.webp",
    mode: "result",
    emoji: "🍎",
    before: 2,
    change: 2,
    action: "add",
    options: [
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "6", label: "6" },
    ],
    correct: "4",
    success: "مُمْتَاز! المَجْمُوعُ أَرْبَعَةٌ.",
  },
  {
    id: "l27_e3_q3",
    title: "أَحْسِبُ المَجْمُوعَ",
    story: "عِنْدَ فَاضِلٍ أَرْبَعُ كُرَاتٍ، وَرَبِحَ ثَلَاثَ كُرَاتٍ.",
    question: "كَمْ صَارَ المَجْمُوعُ؟",
    question_audio_key: "ex3_q3",
    scene_image: "/lessons/v2/lesson27-plus-equals/s4.webp",
    mode: "result",
    emoji: "🔵",
    before: 4,
    change: 3,
    action: "add",
    options: [
      { id: "6", label: "6" },
      { id: "7", label: "7" },
      { id: "8", label: "8" },
    ],
    correct: "7",
    success: "رَائِع! المَجْمُوعُ سَبْعَةٌ.",
  },
  {
    id: "l27_e3_q4",
    title: "أَحْسِبُ المَجْمُوعَ",
    story: "فِي المِقْلَمَةِ خَمْسَةُ أَقْلَامٍ، أَضَفْنَا ثَلَاثَةً.",
    question: "كَمْ صَارَ المَجْمُوعُ؟",
    question_audio_key: "ex3_q4",
    scene_image: "/lessons/v2/lesson27-plus-equals/s5.webp",
    mode: "result",
    emoji: "✏️",
    before: 5,
    change: 3,
    action: "add",
    options: [
      { id: "7", label: "7" },
      { id: "8", label: "8" },
      { id: "9", label: "9" },
    ],
    correct: "8",
    success: "بَارَكَ اللهُ فِيكَ! المَجْمُوعُ ثَمَانِيَةٌ.",
  },
];
