import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";

export const LESSON_25_EXERCISE_AUDIO_BASE = "/audio/teachers/taline/lesson_25_exercises";

export const LESSON_25_EXERCISE_1: AddSubStoryItem[] = [
  {
    id: "l25_e1_q1",
    title: "أُضيف أم آخذ؟",
    story: "رَحْمَةُ عِنْدَهَا ثَلَاثُ حَبَّاتِ حَلْوَى، أَضَفْنَا لَهَا حَبَّةً أُخْرَى.",
    question: "هَلْ هَذِهِ وَضْعِيَّةُ جَمْعٍ أَمْ طَرْحٍ؟",
    question_audio_key: "ex1_q1",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s2.webp",
    mode: "classify",
    emoji: "🍬",
    before: 3,
    change: 1,
    action: "add",
    options: [
      { id: "add", label: "جَمْع", emoji: "➕" },
      { id: "sub", label: "طَرْح", emoji: "➖" },
    ],
    correct: "add",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e1_q2",
    title: "أُضيف أم آخذ؟",
    story: "فَاضِلٌ عِنْدَهُ سَبْعُ كُرَاتٍ، أَخَذَ مِنْهَا ثَلَاثَ كُرَاتٍ.",
    question: "هَلْ هَذِهِ وَضْعِيَّةُ جَمْعٍ أَمْ طَرْحٍ؟",
    question_audio_key: "ex1_q2",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s3.webp",
    mode: "classify",
    emoji: "🔵",
    before: 7,
    change: 3,
    action: "sub",
    options: [
      { id: "add", label: "جَمْع", emoji: "➕" },
      { id: "sub", label: "طَرْح", emoji: "➖" },
    ],
    correct: "sub",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e1_q3",
    title: "أُضيف أم آخذ؟",
    story: "فِي السَّلَّةِ خَمْسُ كُبَّاتِ صُوفٍ، أَضَفْنَا إِلَيْهَا أَرْبَعَ كُبَّاتٍ.",
    question: "هَلْ هَذِهِ وَضْعِيَّةُ جَمْعٍ أَمْ طَرْحٍ؟",
    question_audio_key: "ex1_q3",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s4.webp",
    mode: "classify",
    emoji: "🧶",
    before: 5,
    change: 4,
    action: "add",
    options: [
      { id: "add", label: "جَمْع", emoji: "➕" },
      { id: "sub", label: "طَرْح", emoji: "➖" },
    ],
    correct: "add",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e1_q4",
    title: "أُضيف أم آخذ؟",
    story: "فِي العُلْبَةِ سِتُّ بَيْضَاتٍ، أَخَذَتْ سِيرِينُ أَرْبَعَ بَيْضَاتٍ.",
    question: "هَلْ هَذِهِ وَضْعِيَّةُ جَمْعٍ أَمْ طَرْحٍ؟",
    question_audio_key: "ex1_q4",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s5.webp",
    mode: "classify",
    emoji: "🥚",
    before: 6,
    change: 4,
    action: "sub",
    options: [
      { id: "add", label: "جَمْع", emoji: "➕" },
      { id: "sub", label: "طَرْح", emoji: "➖" },
    ],
    correct: "sub",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e1_q5",
    title: "أُضيف أم آخذ؟",
    story: "عَلَى الطَّاوِلَةِ أَرْبَعُ حَبَّاتِ حَلْوَى، أَضَفْنَا ثَلَاثَ حَبَّاتٍ أُخْرَى.",
    question: "هَلْ هَذِهِ وَضْعِيَّةُ جَمْعٍ أَمْ طَرْحٍ؟",
    question_audio_key: "ex1_q5",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s1.webp",
    mode: "classify",
    emoji: "🍬",
    before: 4,
    change: 3,
    action: "add",
    options: [
      { id: "add", label: "جَمْع", emoji: "➕" },
      { id: "sub", label: "طَرْح", emoji: "➖" },
    ],
    correct: "add",
    success: "أَحْسَنْتَ!",
  },
];
