import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";
import { LESSON_25_EXERCISE_AUDIO_BASE } from "./lesson25_exercise1";

export { LESSON_25_EXERCISE_AUDIO_BASE };

export const LESSON_25_EXERCISE_3: AddSubStoryItem[] = [
  {
    id: "l25_e3_q1",
    title: "أَحْسِبُ النَّتِيجَةَ",
    story: "رَحْمَةُ مَعَهَا ثَلَاثُ حَبَّاتٍ، أَضَفْنَا حَبَّةً.",
    question: "كَمْ صَارَ عِنْدَ رَحْمَةَ؟",
    question_audio_key: "ex3_q1",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s2.webp",
    mode: "result",
    emoji: "🍬",
    before: 3,
    change: 1,
    action: "add",
    options: [
      { id: "2", label: "2" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
    ],
    correct: "4",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e3_q2",
    title: "أَحْسِبُ النَّتِيجَةَ",
    story: "فَاضِلٌ عِنْدَهُ سَبْعُ كُرَاتٍ، أَخَذَ ثَلَاثًا.",
    question: "كَمْ بَقِيَ عِنْدَ فَاضِلٍ؟",
    question_audio_key: "ex3_q2",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s3.webp",
    mode: "result",
    emoji: "🔵",
    before: 7,
    change: 3,
    action: "sub",
    options: [
      { id: "4", label: "4" },
      { id: "5", label: "5" },
      { id: "10", label: "10" },
    ],
    correct: "4",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e3_q3",
    title: "أَحْسِبُ النَّتِيجَةَ",
    story: "فِي السَّلَّةِ خَمْسُ كُبَّاتِ صُوفٍ، أَضَفْنَا أَرْبَعًا.",
    question: "كَمْ كُبَّةَ صُوفٍ صَارَتْ؟",
    question_audio_key: "ex3_q3",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s4.webp",
    mode: "result",
    emoji: "🧶",
    before: 5,
    change: 4,
    action: "add",
    options: [
      { id: "7", label: "7" },
      { id: "9", label: "9" },
      { id: "1", label: "1" },
    ],
    correct: "9",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e3_q4",
    title: "أَحْسِبُ النَّتِيجَةَ",
    story: "فِي العُلْبَةِ سِتُّ بَيْضَاتٍ، أَخَذْنَا أَرْبَعًا.",
    question: "كَمْ بَيْضَةً بَقِيَتْ؟",
    question_audio_key: "ex3_q4",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s5.webp",
    mode: "result",
    emoji: "🥚",
    before: 6,
    change: 4,
    action: "sub",
    options: [
      { id: "2", label: "2" },
      { id: "4", label: "4" },
      { id: "10", label: "10" },
    ],
    correct: "2",
    success: "أَحْسَنْتَ!",
  },
  {
    id: "l25_e3_q5",
    title: "أَحْسِبُ النَّتِيجَةَ",
    story: "أَرْبَعُ حَبَّاتِ حَلْوَى، أَضَفْنَا إِلَيْهَا ثَلَاثًا.",
    question: "كَمْ حَبَّةَ حَلْوَى صَارَتْ؟",
    question_audio_key: "ex3_q5",
    scene_image: "/lessons/v2/lesson25-add-sub-situations/s1.webp",
    mode: "result",
    emoji: "🍬",
    before: 4,
    change: 3,
    action: "add",
    options: [
      { id: "6", label: "6" },
      { id: "7", label: "7" },
      { id: "8", label: "8" },
    ],
    correct: "7",
    success: "أَحْسَنْتَ!",
  },
];
