import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";
import { LESSON_28_EXERCISE_AUDIO_BASE } from "./lesson28_exercise1";

export { LESSON_28_EXERCISE_AUDIO_BASE };

export const LESSON_28_EXERCISE_2: AddSubStoryItem[] = [
  {
    id: "l28_e2_q1",
    title: "أَحْسِبُ البَاقِيَ",
    story: "عِنْدَنَا سَبْعُ حَبَّاتِ أَنَانَاسٍ، أَخَذْنَا أَرْبَعًا.",
    question: "كَمْ حَبَّةً بَقِيَتْ؟",
    question_audio_key: "ex2_q1",
    scene_image: "/lessons/v2/lesson28-minus-equals/s2.webp",
    mode: "result",
    emoji: "🍍",
    before: 7,
    change: 4,
    action: "sub",
    options: [
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
    ],
    correct: "3",
    success: "أَحْسَنْتَ! بَقِيَتْ ثَلَاثُ حَبَّاتٍ.",
  },
  {
    id: "l28_e2_q2",
    title: "أَحْسِبُ البَاقِيَ",
    story: "عِنْدَ فَاضِلٍ ثَمَانِي كُرَاتٍ، أَخَذْنَا كُرَتَيْنِ.",
    question: "كَمْ كُرَةً بَقِيَتْ؟",
    question_audio_key: "ex2_q2",
    scene_image: "/lessons/v2/lesson28-minus-equals/s3.webp",
    mode: "result",
    emoji: "🔵",
    before: 8,
    change: 2,
    action: "sub",
    options: [
      { id: "5", label: "5" },
      { id: "6", label: "6" },
      { id: "7", label: "7" },
    ],
    correct: "6",
    success: "مُمْتَاز! بَقِيَتْ سِتُّ كُرَاتٍ.",
  },
  {
    id: "l28_e2_q3",
    title: "أَحْسِبُ البَاقِيَ",
    story: "فِي الحَدِيقَةِ سِتُّ زَهْرَاتٍ، ذَبُلَتْ زَهْرَتَانِ.",
    question: "كَمْ زَهْرَةً بَقِيَتْ؟",
    question_audio_key: "ex2_q3",
    scene_image: "/lessons/v2/lesson28-minus-equals/s4.webp",
    mode: "result",
    emoji: "🌸",
    before: 6,
    change: 2,
    action: "sub",
    options: [
      { id: "3", label: "3" },
      { id: "4", label: "4" },
      { id: "5", label: "5" },
    ],
    correct: "4",
    success: "رَائِع! بَقِيَتْ أَرْبَعُ زَهْرَاتٍ.",
  },
  {
    id: "l28_e2_q4",
    title: "أَحْسِبُ البَاقِيَ",
    story: "فِي المِقْلَمَةِ تِسْعَةُ أَقْلَامٍ، أَخَذْنَا ثَلَاثَةً.",
    question: "كَمْ قَلَمًا بَقِيَ؟",
    question_audio_key: "ex2_q4",
    scene_image: "/lessons/v2/lesson28-minus-equals/s5.webp",
    mode: "result",
    emoji: "✏️",
    before: 9,
    change: 3,
    action: "sub",
    options: [
      { id: "5", label: "5" },
      { id: "6", label: "6" },
      { id: "7", label: "7" },
    ],
    correct: "6",
    success: "بَطَل! بَقِيَتْ سِتَّةُ أَقْلَامٍ.",
  },
];
