import type { AddSubStoryItem } from "../exercises-v2/AddSubStoryLabV2";
import { LESSON_27_EXERCISE_AUDIO_BASE } from "./lesson27_exercise1";

export { LESSON_27_EXERCISE_AUDIO_BASE };

export const LESSON_27_EXERCISE_4: AddSubStoryItem[] = [
  {
    id: "l27_e4_q1",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "عِنْدَ رَحْمَةَ ثَلَاثُ تُفَّاحَاتٍ، وَأَضَفْنَا تُفَّاحَتَيْنِ.",
    question: "مَا عَمَلِيَّةُ الجَمْعِ الصَّحِيحَةُ؟",
    question_audio_key: "ex4_q1",
    scene_image: "/lessons/v2/lesson27-plus-equals/s2.webp",
    mode: "operation",
    emoji: "🍎",
    before: 3,
    change: 2,
    action: "add",
    options: [
      { id: "3+2", label: "3 + 2 = 5", emoji: "➕" },
      { id: "3-2", label: "3 - 2 = 1", emoji: "➖" },
      { id: "2+5", label: "2 + 5 = 7", emoji: "➕" },
    ],
    correct: "3+2",
    success: "أَحْسَنْتَ! ثَلَاثَةٌ زَائِدُ اثْنَيْنِ يُسَاوِي خَمْسَةً.",
  },
  {
    id: "l27_e4_q2",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "عِنْدَ فَاضِلٍ أَرْبَعُ كُرَاتٍ، وَرَبِحَ ثَلَاثَ كُرَاتٍ.",
    question: "مَا عَمَلِيَّةُ الجَمْعِ الصَّحِيحَةُ؟",
    question_audio_key: "ex4_q2",
    scene_image: "/lessons/v2/lesson27-plus-equals/s3.webp",
    mode: "operation",
    emoji: "🔵",
    before: 4,
    change: 3,
    action: "add",
    options: [
      { id: "4-3", label: "4 - 3 = 1", emoji: "➖" },
      { id: "4+3", label: "4 + 3 = 7", emoji: "➕" },
      { id: "3+3", label: "3 + 3 = 6", emoji: "➕" },
    ],
    correct: "4+3",
    success: "مُمْتَاز! أَرْبَعَةٌ زَائِدُ ثَلَاثَةٍ يُسَاوِي سَبْعَةً.",
  },
  {
    id: "l27_e4_q3",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "فِي المِقْلَمَةِ قَلَمَانِ، أَضَفْنَا خَمْسَةَ أَقْلَامٍ.",
    question: "مَا عَمَلِيَّةُ الجَمْعِ الصَّحِيحَةُ؟",
    question_audio_key: "ex4_q3",
    scene_image: "/lessons/v2/lesson27-plus-equals/s4.webp",
    mode: "operation",
    emoji: "✏️",
    before: 2,
    change: 5,
    action: "add",
    options: [
      { id: "2+5", label: "2 + 5 = 7", emoji: "➕" },
      { id: "5-2", label: "5 - 2 = 3", emoji: "➖" },
      { id: "2+4", label: "2 + 4 = 6", emoji: "➕" },
    ],
    correct: "2+5",
    success: "رَائِع! اثْنَانِ زَائِدُ خَمْسَةٍ يُسَاوِي سَبْعَةً.",
  },
  {
    id: "l27_e4_q4",
    title: "أَخْتَارُ العَمَلِيَّةَ",
    story: "فِي السَّلَّةِ أَرْبَعُ زَهْرَاتٍ، أَضَفْنَا أَرْبَعَ زَهْرَاتٍ.",
    question: "مَا عَمَلِيَّةُ الجَمْعِ الصَّحِيحَةُ؟",
    question_audio_key: "ex4_q4",
    scene_image: "/lessons/v2/lesson27-plus-equals/s5.webp",
    mode: "operation",
    emoji: "🌸",
    before: 4,
    change: 4,
    action: "add",
    options: [
      { id: "4-4", label: "4 - 4 = 0", emoji: "➖" },
      { id: "4+3", label: "4 + 3 = 7", emoji: "➕" },
      { id: "4+4", label: "4 + 4 = 8", emoji: "➕" },
    ],
    correct: "4+4",
    success: "بَطَل! أَرْبَعَةٌ زَائِدُ أَرْبَعَةٍ يُسَاوِي ثَمَانِيَةً.",
  },
];
