import type { EquationBuilderItem } from "../exercises-v2/EquationBuilderV2";

export const LESSON_28_EXERCISE_AUDIO_BASE =
  "/audio/teachers/khalil/lesson_28_exercises";

export const LESSON_28_EXERCISE_1: EquationBuilderItem[] = [
  {
    id: "l28_e1_q1",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q1",
    scene_image: "/lessons/v2/lesson28-minus-equals/s1.webp",
    mode: "missing-symbol",
    emoji: "🍍",
    before: 7,
    change: 3,
    result: 4,
    action: "sub",
    equation: ["7", "__", "3", "=", "4"],
    options: [
      { id: "minus", label: "−" },
      { id: "equals", label: "=" },
    ],
    correct: "minus",
    success: "أَحْسَنْتَ! وَضَعْتَ رَمْزَ نَاقِصٍ.",
  },
  {
    id: "l28_e1_q2",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q2",
    scene_image: "/lessons/v2/lesson28-minus-equals/s2.webp",
    mode: "missing-symbol",
    emoji: "🔵",
    before: 7,
    change: 3,
    result: 4,
    action: "sub",
    equation: ["7", "−", "3", "__", "4"],
    options: [
      { id: "equals", label: "=" },
      { id: "minus", label: "−" },
    ],
    correct: "equals",
    success: "مُمْتَاز! وَضَعْتَ رَمْزَ يُسَاوِي.",
  },
  {
    id: "l28_e1_q3",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q3",
    scene_image: "/lessons/v2/lesson28-minus-equals/s3.webp",
    mode: "missing-symbol",
    emoji: "🌸",
    before: 6,
    change: 2,
    result: 4,
    action: "sub",
    equation: ["6", "__", "2", "=", "4"],
    options: [
      { id: "equals", label: "=" },
      { id: "minus", label: "−" },
    ],
    correct: "minus",
    success: "رَائِع! هَذَا هُوَ رَمْزُ نَاقِصٍ.",
  },
  {
    id: "l28_e1_q4",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q4",
    scene_image: "/lessons/v2/lesson28-minus-equals/s4.webp",
    mode: "missing-symbol",
    emoji: "✏️",
    before: 8,
    change: 2,
    result: 6,
    action: "sub",
    equation: ["8", "−", "2", "__", "6"],
    options: [
      { id: "minus", label: "−" },
      { id: "equals", label: "=" },
    ],
    correct: "equals",
    success: "مُمْتَاز! أَكْمَلْتَ العَمَلِيَّةَ.",
  },
];
