import type { UnitMeasurePathItem } from "../exercises-v2/UnitMeasurePathV2";

export const LESSON_33_EXERCISE_4_AUDIO_BASE =
  "/audio/teachers/taline/lesson_33_amusement_lengths/exercises";

export const LESSON_33_EXERCISE_4 = [
  {
    mode: "map",
    title: "أَخْتَارُ المَسَارَ",
    question: "أَيُّ مَسَارٍ يَجْعَلُ الفَأْرَ يَصِلُ أَسْرَعَ؟",
    question_audio_key: "ex4_q1",
    background_image: "/lessons/v2/lesson33-amusement-lengths/s4.webp",
    routes: [
      {
        id: "green",
        label: "المسار الأخضر",
        color: "#20A567",
        units: 4,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
      {
        id: "blue",
        label: "المسار الأزرق",
        color: "#3B82F6",
        units: 6,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
      {
        id: "orange",
        label: "المسار البرتقالي",
        color: "#F28C28",
        units: 8,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
    ],
    options: ["المسار الأخضر", "المسار الأزرق", "المسار البرتقالي"],
    correct: "المسار الأخضر",
    explanation: "أحسنت، المسار الأخضر هو الأقصر.",
  },
  {
    mode: "map",
    title: "أَخْتَارُ المَسَارَ",
    question: "أَيُّ مَسَارٍ يَجْعَلُ السُّلَحْفَاةَ تَقْطَعُ وَحَدَاتٍ أَكْثَرَ؟",
    question_audio_key: "ex4_q2",
    background_image: "/lessons/v2/lesson33-amusement-lengths/s5.webp",
    routes: [
      {
        id: "purple",
        label: "المسار البنفسجي",
        color: "#7B57D1",
        units: 3,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
      {
        id: "red",
        label: "المسار الأحمر",
        color: "#E0574F",
        units: 5,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
      {
        id: "blue",
        label: "المسار الأزرق",
        color: "#3B82F6",
        units: 7,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
    ],
    options: ["المسار البنفسجي", "المسار الأحمر", "المسار الأزرق"],
    correct: "المسار الأزرق",
    explanation: "أحسنت، المسار الأزرق هو الأطول.",
  },
  {
    mode: "map",
    title: "أَخْتَارُ المَسَارَ",
    question: "أَيُّ مَسَارٍ يَجْعَلُ الفَأْرَ يَصِلُ أَسْرَعَ؟",
    question_audio_key: "ex4_q3",
    background_image: "/lessons/v2/lesson33-amusement-lengths/s5.webp",
    routes: [
      {
        id: "orange",
        label: "المسار البرتقالي",
        color: "#F28C28",
        units: 6,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
      {
        id: "green",
        label: "المسار الأخضر",
        color: "#20A567",
        units: 5,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
      {
        id: "purple",
        label: "المسار البنفسجي",
        color: "#7B57D1",
        units: 4,
        start: { label: "الفأر", kind: "mouse", color: "#94A3B8" },
        end: { label: "الجبن", kind: "cheese", color: "#FFD54A" },
      },
    ],
    options: ["المسار البرتقالي", "المسار الأخضر", "المسار البنفسجي"],
    correct: "المسار البنفسجي",
    explanation: "أحسنت، المسار البنفسجي هو الأقصر.",
  },
  {
    mode: "map",
    title: "أَخْتَارُ المَسَارَ",
    question: "أَيُّ مَسَارٍ يَجْعَلُ السُّلَحْفَاةَ تَقْطَعُ وَحَدَاتٍ أَكْثَرَ؟",
    question_audio_key: "ex4_q4",
    background_image: "/lessons/v2/lesson33-amusement-lengths/s6.webp",
    routes: [
      {
        id: "red",
        label: "المسار الأحمر",
        color: "#E0574F",
        units: 5,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
      {
        id: "blue",
        label: "المسار الأزرق",
        color: "#3B82F6",
        units: 8,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
      {
        id: "green",
        label: "المسار الأخضر",
        color: "#20A567",
        units: 6,
        start: { label: "السلحفاة", kind: "turtle", color: "#75BF72" },
        end: { label: "الورقة", kind: "leaf", color: "#5DBB63" },
      },
    ],
    options: ["المسار الأحمر", "المسار الأزرق", "المسار الأخضر"],
    correct: "المسار الأزرق",
    explanation: "أحسنت، المسار الأزرق هو الأطول.",
  },
] satisfies UnitMeasurePathItem[];
