import type { EquationBuilderItem } from "../exercises-v2/EquationBuilderV2";

export const LESSON_27_EXERCISE_AUDIO_BASE =
  "/audio/teachers/taline/lesson_27_exercises";

export const LESSON_27_EXERCISE_1: EquationBuilderItem[] = [
  {
    id: "l27_e1_q1",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q1",
    scene_image: "/lessons/v2/lesson27-plus-equals/s1.webp",
    mode: "missing-symbol",
    emoji: "🍎",
    before: 3,
    change: 2,
    result: 5,
    action: "add",
    equation: ["3", "__", "2", "=", "5"],
    options: [
      { id: "plus", label: "+" },
      { id: "equals", label: "=" },
    ],
    correct: "plus",
    success: "أَحْسَنْتَ! وَضَعْتَ رَمْزَ زَائِدٍ.",
  },
  {
    id: "l27_e1_q2",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q2",
    scene_image: "/lessons/v2/lesson27-plus-equals/s2.webp",
    mode: "missing-symbol",
    emoji: "🔵",
    before: 4,
    change: 3,
    result: 7,
    action: "add",
    equation: ["4", "+", "3", "__", "7"],
    options: [
      { id: "equals", label: "=" },
      { id: "plus", label: "+" },
    ],
    correct: "equals",
    success: "مُمْتَاز! وَضَعْتَ رَمْزَ يُسَاوِي.",
  },
  {
    id: "l27_e1_q3",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q3",
    scene_image: "/lessons/v2/lesson27-plus-equals/s3.webp",
    mode: "missing-symbol",
    emoji: "✏️",
    before: 2,
    change: 4,
    result: 6,
    action: "add",
    equation: ["2", "__", "4", "=", "6"],
    options: [
      { id: "equals", label: "=" },
      { id: "plus", label: "+" },
    ],
    correct: "plus",
    success: "رَائِع! هَذَا هُوَ رَمْزُ زَائِدٍ.",
  },
  {
    id: "l27_e1_q4",
    title: "أَضَعُ الرَّمْزَ المُنَاسِبَ",
    question: "اِخْتَرِ الرَّمْزَ المُنَاسِبَ لِإِكْمَالِ العَمَلِيَّةِ.",
    question_audio_key: "ex1_q4",
    scene_image: "/lessons/v2/lesson27-plus-equals/s4.webp",
    mode: "missing-symbol",
    emoji: "🌸",
    before: 4,
    change: 4,
    result: 8,
    action: "add",
    equation: ["4", "+", "4", "__", "8"],
    options: [
      { id: "plus", label: "+" },
      { id: "equals", label: "=" },
    ],
    correct: "equals",
    success: "مُمْتَاز! أَكْمَلْتَ العَمَلِيَّةَ.",
  },
];
