import type { EquationBuilderItem } from "../exercises-v2/EquationBuilderV2";
import { LESSON_27_EXERCISE_AUDIO_BASE } from "./lesson27_exercise1";

export { LESSON_27_EXERCISE_AUDIO_BASE };

export const LESSON_27_EXERCISE_2: EquationBuilderItem[] = [
  {
    id: "l27_e2_q1",
    title: "أَبْنِي عَمَلِيَّةَ الجَمْعِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الجَمْعِ الصَّحِيحَةِ.",
    question_audio_key: "ex2_q1",
    scene_image: "/lessons/v2/lesson27-plus-equals/s2.webp",
    mode: "build-equation",
    emoji: "🍬",
    before: 2,
    change: 1,
    result: 3,
    action: "add",
    equation: ["2", "+", "1", "=", "3"],
    bank: ["=", "1", "3", "+", "2"],
    success: "أَحْسَنْتَ! بَنَيْتَ العَمَلِيَّةَ.",
  },
  {
    id: "l27_e2_q2",
    title: "أَبْنِي عَمَلِيَّةَ الجَمْعِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الجَمْعِ الصَّحِيحَةِ.",
    question_audio_key: "ex2_q2",
    scene_image: "/lessons/v2/lesson27-plus-equals/s3.webp",
    mode: "build-equation",
    emoji: "🍎",
    before: 3,
    change: 2,
    result: 5,
    action: "add",
    equation: ["3", "+", "2", "=", "5"],
    bank: ["5", "2", "=", "3", "+"],
    success: "مُمْتَاز! العَمَلِيَّةُ صَحِيحَةٌ.",
  },
  {
    id: "l27_e2_q3",
    title: "أَبْنِي عَمَلِيَّةَ الجَمْعِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الجَمْعِ الصَّحِيحَةِ.",
    question_audio_key: "ex2_q3",
    scene_image: "/lessons/v2/lesson27-plus-equals/s4.webp",
    mode: "build-equation",
    emoji: "🔵",
    before: 4,
    change: 3,
    result: 7,
    action: "add",
    equation: ["4", "+", "3", "=", "7"],
    bank: ["3", "7", "+", "4", "="],
    success: "رَائِع! أَحْسَنْتَ التَّرْتِيبَ.",
  },
  {
    id: "l27_e2_q4",
    title: "أَبْنِي عَمَلِيَّةَ الجَمْعِ",
    question: "رَتِّبِ البِطَاقَاتِ لِبِنَاءِ عَمَلِيَّةِ الجَمْعِ الصَّحِيحَةِ.",
    question_audio_key: "ex2_q4",
    scene_image: "/lessons/v2/lesson27-plus-equals/s5.webp",
    mode: "build-equation",
    emoji: "🌸",
    before: 4,
    change: 4,
    result: 8,
    action: "add",
    equation: ["4", "+", "4", "=", "8"],
    bank: ["4", "8", "=", "+", "4"],
    success: "بَطَل! بَنَيْتَ العَمَلِيَّةَ كَامِلَةً.",
  },
];
